---
- name: Health check and safe remediation on Linux EC2 nodes
  hosts: linux_servers
  become: true
  gather_facts: true

  roles:
    - role: health_check
      tags:
        - health
        - check

    - role: remediation
      tags:
        - fix
        - remediation
